version: '3.7'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  clickhouse:
    image: clickhouse/clickhouse-server:23
    restart: always
    environment:
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: password
      CLICKHOUSE_DB: logbun
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
    ports:
      - 19000:9000
      - 18123:8123

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080

  tabix:
    image: spoonest/clickhouse-tabix-web-client
    restart: always
    depends_on:
      - clickhouse
    ports:
      - 8090:80

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  minio:
    image: minio/minio
    ports:
      - 9000:9000 # server
      - 9001:9001 # web ui
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data

volumes:
  postgres_data:
  clickhouse_data:
  minio_storage:
