[phases.setup]
nixPkgs = ['nodejs_21', 'pnpm-8_x']

[phases.install]
cmds = [
  'npm install -g corepack && corepack enable',
  'pnpm i --frozen-lockfile',
]

[phases.build]
cmds = ['pnpm build']

[start]
cmd = 'pnpm start'

[variables]
NODE_ENV = 'production'
