name: Publish CDN
on:
  push:
    branches: main
    # tags:
    #   - 'v[0-9]+.[0-9]+.[0-9]+'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install -no-frozen-lockfile

      - name: Build sdks
        run: pnpm build:sdks

      - name: Publish to CDN
        run: node ../../packages/server-utils/scripts/cdn-upload.cjs dist/*.min.js
        working-directory: './sdks/js'
        env:
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_REGION: ${{ secrets.S3_REGION }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_CDN_BUCKET: ${{ secrets.S3_CDN_BUCKET }}
          CDN_URL: ${{ secrets.CDN_URL }}
          CDN_ACCESS_KEY: ${{ secrets.CDN_ACCESS_KEY }}
